# Generated by Django 2.0.6 on 2018-09-02 02:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_readdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 2, 2, 37, 16, 587938, tzinfo=utc), verbose_name='点击阅读日期'),
        ),
    ]
