# Generated by Django 2.0.6 on 2018-09-02 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytest', '0007_auto_20180901_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='blog',
        ),
        migrations.DeleteModel(
            name='ReadNUm',
        ),
    ]
