# Generated by Django 2.0.6 on 2018-08-06 06:03

# 生成的迁移文件 --- python3 manage.py makemigrations 用来描述数据库的结构
# python3 manage.py migrate 应用迁移 开始在db.sqlite3 里创建数据库


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
