# Generated by Django 2.0.6 on 2018-08-31 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20180808_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='readed_num',
            field=models.IntegerField(default=0, verbose_name='阅读点击量'),
        ),
    ]
